### ISSUE TITLE
Tracking issue for examples and tests

### ISSUE THREAD

**Issue by igrr** [espressif/idf-extra-components#388]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Some of the components in this repo are missing examples and/or example tests. This issue tracks adding the missing examples.

If the component has an empty test_app and the functionality can be adequately using the example only, remove the test_app when adding the example.

### Examples

These components don't have examples at all:

- [ ] ccomp_timer
- [ ] dhara
- [ ] esp_encrypted_img
- [ ] esp_serial_slave_link
- [ ] expat
- [ ] jsmn
- [ ] json_generator
- [ ] json_parser
- [ ] libpng
- [ ] libsodium
- [ ] nghttp
- [ ] onewire_bus
- [ ] pcap
- [ ] pid_ctrl
- [ ] qrcode
- [ ] quirc
- [ ] zlib

## Example tests

These components don't have example tests:

- [ ] eigen
- [ ] esp_delta_ota
- [ ] esp_jpeg
- [ ] esp_lcd_qemu_rgb
- [ ] iqmath
- [ ] led_strip
- [ ] network_provisioning
- [ ] spi_nand_flash
- [ ] supertinycron
- [ ] thorvg

If the existing example depends on some specific hardware setup, consider adding a simpler test_app which can be run on generic hardware or mocking hardware dependencies.
